braindump_and_escapeerrands/braindump/braindump/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # Admin
    # host/admin/
    url(r'^admin/', admin.site.urls),

    # host/
    url(r'^', include('interface.urls')),
]

braindump_and_escapeerrands/braindump/interface/urls.py
from django.conf.urls import url
from interface.views import goalapis, sessionapis
from interface.views import webpages

app_name = 'interface'

urlpatterns = [

    # webpages
    # host/scratch/
    url(r'^scratch/$', webpages.scratch, name='scratch'),
    # host/
    url(r'^$', webpages.index, name='index'),
    # host/goal/glance/
    url(r'^goal/glance/$', webpages.goal_glance, name='goal_glance'),
    # host/goal/snapshot_viewer/
    url(r'^goal/snapshot_viewer/$', webpages.goal_snapshot_viewer, name='goal_snapshot_viewer'),

    # sessionapis
    # host/login/<POST password>
    url(r'^login/$', sessionapis.login, name='login'),
    # host/logout/
    url(r'^logout/$', sessionapis.logout, name='logout'),

    # goalapis
    # read
    # host/goal/read/regex/?regex=REGEX_PATTERN & global_search=(1 or 0)
    url(r'^goal/read/regex/$', goalapis.read_regex, name='goal_read_regex'),
    # host/goal/read/family/pk
    url(r'^goal/read/family/(?P<pk>[1-9][0-9]*)/$', goalapis.read_family, name='goal_read_family'),
    # write
    # host/goal/create/<POST description, deadline>
    url(r'^goal/create/$', goalapis.create, name='goal_create'),
    # host/goal/update/<POST id, description, deadline>
    url(r'^goal/update/$', goalapis.update, name='goal_update'),
    # host/goal/chain_update/<POST id, description, deadline>
    url(r'^goal/chain_update/$', goalapis.chain_update, name='goal_chain_update'),
    # host/goal/delete/if_single/<POST id>
    url(r'^goal/delete/if_single/$', goalapis.delete_if_single, name='goal_delete_if_single'),
    # host/goal/add_relation/<POST parent_id, child_id>
    url(r'^goal/add_relation/$', goalapis.add_relation, name='goal_add_relation'),
    # host/goal/remove_relation/<POST parent_id, child_id>
    url(r'^goal/remove_relation/$', goalapis.remove_relation, name='goal_remove_relation'),
    # host/goal/toggle/is_achieved/pk/
    url(r'^goal/toggle/is_achieved/(?P<pk>[1-9][0-9]*)/$', goalapis.toggle_is_achieved,
        name='goal_toggle_is_achieved'),
    # host/goal/snapshot/month/<POST year, month>
    url(r'^goal/snapshot/month/$', goalapis.snapshot_month, name='goal_snapshot_month'),
]

braindump_and_escapeerrands/braindump/interface/views/goalapis.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.utils.datastructures import MultiValueDictKeyError
from datetime import datetime as dt

from django.views.decorators.csrf import csrf_exempt

from interface.views.responsewrapper import ResponseWrapper
import re
import json
from core.query.goal import Goal
from interface.views.sessionapis import is_session_active


def jsonize_goal(goal):
    deadline = None
    if goal.deadline is not None:
        deadline = {
            'year': goal.deadline.year,
            'month': goal.deadline.month,
            'day': goal.deadline.day,
            'hour': goal.deadline.hour,
            'minute': goal.deadline.minute,
            'second': goal.deadline.second,
            'microsecond': goal.deadline.microsecond,
        }
    parent_ids = []
    for parent in goal.get_parents():
        parent_ids.append(parent.id)
    child_ids = []
    for child in goal.get_children():
        child_ids.append(child.id)

    json_goal = {
        'description': goal.description,
        'deadline': deadline,
        'is_achieved': goal.is_achieved,
        'id': goal.id,
        'parent_ids': parent_ids,
        'child_ids': child_ids,
        'color': goal.color,
    }
    return json_goal


@csrf_exempt
def read_regex(request):
    if is_session_active(request.session):
        if request.method == 'POST':
            try:
                regex = request.POST['regex']
                is_global_search = request.POST['is_global_search']

                matched_goal_family_subsets = Goal.read_regex(regex, is_global_search)

                json_goal_family_subsets = []
                for family_subset in matched_goal_family_subsets:
                    json_family_subset = []
                    for goal in family_subset:
                        json_family_subset.append(jsonize_goal(goal))
                    json_goal_family_subsets.append(json_family_subset)

                return HttpResponse(
                    json.dumps(ResponseWrapper.of(json_goal_family_subsets, ResponseWrapper.ARRAY_RESPONSE)))
            except MultiValueDictKeyError:
                return HttpResponse(json.dumps(ResponseWrapper.error('Improper data')))
            except re.error:
                return HttpResponse(json.dumps(ResponseWrapper.error('Not proper regex')))
        else:
            return HttpResponse(json.dumps(ResponseWrapper.error('Invalid request')))
    else:
        return HttpResponse(json.dumps(ResponseWrapper.error('Invalid session')))


@csrf_exempt
def read_family(request, pk):
    if is_session_active(request.session):
        if request.method == 'POST':
            try:
                goal_family = Goal.read_family(pk)
                json_family = []
                for member in goal_family:
                    json_family.append(jsonize_goal(member))

                return HttpResponse(json.dumps(ResponseWrapper.of(json_family, ResponseWrapper.ARRAY_RESPONSE)))
            except ObjectDoesNotExist:
                return HttpResponse(json.dumps(ResponseWrapper.error('No goal with such id')))
        else:
            return HttpResponse(json.dumps(ResponseWrapper.error('Invalid request')))
    else:
        return HttpResponse(json.dumps(ResponseWrapper.error('Invalid session')))


@csrf_exempt
def create(request):
    if is_session_active(request.session):
        if request.method == 'POST':
            try:
                description = request.POST['description']
                deadline = json.loads(request.POST['deadline'])
                color = request.POST['color']

                if deadline is not None:
                    deadline = dt(year=deadline['year'],
                                  month=deadline['month'],
                                  day=deadline['day'],
                                  hour=deadline['hour'],
                                  minute=deadline['minute'],
                                  second=deadline['second'],
                                  microsecond=deadline['microsecond'])
                is_created = Goal.create(description, deadline, color)

                if is_created[0] is True:
                    return HttpResponse(
                        json.dumps(ResponseWrapper.of(jsonize_goal(is_created[1]), ResponseWrapper.OBJECT_RESPONSE)))
                else:
                    return HttpResponse(json.dumps(ResponseWrapper.error(is_created[1])))

            except (ValueError, TypeError, MultiValueDictKeyError):
                return HttpResponse(json.dumps(ResponseWrapper.error('Improper data')))
        else:
            return HttpResponse(json.dumps(ResponseWrapper.error('Invalid request')))
    else:
        return HttpResponse(json.dumps(ResponseWrapper.error('Invalid session')))


@csrf_exempt
def update(request):
    if is_session_active(request.session):
        if request.method == 'POST':
            try:
                pk = request.POST['id']
                description = request.POST['description']
                deadline = json.loads(request.POST['deadline'])
                color = request.POST['color']

                if deadline is not None:
                    deadline = dt(year=deadline['year'],
                                  month=deadline['month'],
                                  day=deadline['day'],
                                  hour=deadline['hour'],
                                  minute=deadline['minute'],
                                  second=deadline['second'],
                                  microsecond=deadline['microsecond'])
                is_updated = Goal.update(pk, description, deadline, color)

                if is_updated[0] is True:
                    return HttpResponse(
                        json.dumps(ResponseWrapper.of(jsonize_goal(is_updated[1]), ResponseWrapper.OBJECT_RESPONSE)))
                else:
                    return HttpResponse(json.dumps(ResponseWrapper.error(is_updated[1])))

            except (ValueError, TypeError, MultiValueDictKeyError):
                return HttpResponse(json.dumps(ResponseWrapper.error('Improper data')))
            except ObjectDoesNotExist:
                return HttpResponse(json.dumps(ResponseWrapper.error('Invalid id')))
        else:
            return HttpResponse(json.dumps(ResponseWrapper.error('Invalid request')))
    else:
        return HttpResponse(json.dumps(ResponseWrapper.error('Invalid session')))


@csrf_exempt
def chain_update(request):
    if is_session_active(request.session):
        if request.method == 'POST':
            try:
                pk = request.POST['id']
                description = request.POST['description']
                deadline = json.loads(request.POST['deadline'])
                color = request.POST['color']

                if deadline is not None:
                    deadline = dt(year=deadline['year'],
                                  month=deadline['month'],
                                  day=deadline['day'],
                                  hour=deadline['hour'],
                                  minute=deadline['minute'],
                                  second=deadline['second'],
                                  microsecond=deadline['microsecond'])
                is_updated = Goal.chain_update(pk, description, deadline, color)

                if is_updated[0] is True:
                    goal_family = is_updated[1]
                    json_family = []
                    for member in goal_family:
                        json_family.append(jsonize_goal(member))

                    return HttpResponse(
                        json.dumps(ResponseWrapper.of(json_family, ResponseWrapper.OBJECT_RESPONSE)))
                else:
                    return HttpResponse(json.dumps(ResponseWrapper.error(is_updated[1])))

            except (ValueError, TypeError, MultiValueDictKeyError):
                return HttpResponse(json.dumps(ResponseWrapper.error('Improper data')))
            except ObjectDoesNotExist:
                return HttpResponse(json.dumps(ResponseWrapper.error('Invalid id')))
        else:
            return HttpResponse(json.dumps(ResponseWrapper.error('Invalid request')))
    else:
        return HttpResponse(json.dumps(ResponseWrapper.error('Invalid session')))


@csrf_exempt
def delete_if_single(request):
    if is_session_active(request.session):
        if request.method == 'POST':
            try:
                pk = request.POST['id']

                is_deleted = Goal.delete_if_single(pk)

                if is_deleted is True:
                    return HttpResponse(json.dumps(ResponseWrapper.of(0, ResponseWrapper.NUMBER_RESPONSE)))
                else:
                    return HttpResponse(json.dumps(ResponseWrapper.error(is_deleted[1])))

            except (ValueError, TypeError, MultiValueDictKeyError):
                return HttpResponse(json.dumps(ResponseWrapper.error('Improper data')))
            except ObjectDoesNotExist:
                return HttpResponse(json.dumps(ResponseWrapper.error('Invalid id')))
        else:
            return HttpResponse(json.dumps(ResponseWrapper.error('Invalid request')))
    else:
        return HttpResponse(json.dumps(ResponseWrapper.error('Invalid session')))


@csrf_exempt
def add_relation(request):
    if is_session_active(request.session):
        if request.method == 'POST':
            try:
                parent_id = int(request.POST['parent_id'])
                child_id = int(request.POST['child_id'])

                was_relation_added = Goal.add_relation(parent_id, child_id)

                if was_relation_added[0] is True:
                    goal_family = was_relation_added[1]
                    json_family = []
                    for member in goal_family:
                        json_family.append(jsonize_goal(member))

braindump_and_escapeerrands/braindump/interface/views/responsewrapper.py
class ResponseWrapper:
    OBJECT_RESPONSE = 1
    ARRAY_RESPONSE = 2
    STRING_RESPONSE = 3
    NUMBER_RESPONSE = 4
    BOOLEAN_RESPONSE = 5
    CHAR_RESPONSE = 6

    ERROR_RESPONSE = -1
    EMPTY_RESPONSE = 0

    @staticmethod
    def of(data, data_type):
        return {'data': data, 'status': data_type}

    @staticmethod
    def error(error):
        return {'error': error, 'status': ResponseWrapper.ERROR_RESPONSE}

    def __init__(self):
        pass

braindump_and_escapeerrands/braindump/interface/views/sessionapis.py
from django.utils.datastructures import MultiValueDictKeyError
from interface.views.responsewrapper import ResponseWrapper
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
import json

PASSWORD = 'airturtle'
SESSION_KEY = 'loggedIn'
SESSION_VALUE = 'yes'


def is_session_active(session):
    try:
        return session[SESSION_KEY] == SESSION_VALUE
    except KeyError:
        return False


@csrf_exempt
def login(request):
    if request.method == 'POST':
        try:
          password = request.POST['password']
          if password == PASSWORD:
              request.session[SESSION_KEY] = SESSION_VALUE
              return HttpResponse(json.dumps(ResponseWrapper.of(0, ResponseWrapper.NUMBER_RESPONSE)))
          else:
              return HttpResponse(json.dumps(ResponseWrapper.error('Incorrect Password')))
        except (ValueError, TypeError, MultiValueDictKeyError):
            return HttpResponse(json.dumps(ResponseWrapper.error('Improper data')))
    else:
        return HttpResponse(json.dumps(ResponseWrapper.error('Invalid request')))


@csrf_exempt
def logout(request):
    request.session.clear()
    return HttpResponse(json.dumps(ResponseWrapper.of(0, ResponseWrapper.NUMBER_RESPONSE)))

braindump_and_escapeerrands/braindump/interface/views/webpages.py
from django.shortcuts import render
from interface.views.sessionapis import is_session_active


def index(request):
    if is_session_active(request.session):
        context = {'isSessionActive': True}
    else:
        context = {'isSessionActive': False}
    return render(request, 'interface/index/index.html', context)


def goal_glance(request):
    return render(request, 'interface/goal/glance.html')


def goal_snapshot_viewer(request):
    return render(request, 'interface/goal/snapshot_viewer.html')


def scratch(request):
    return render(request, 'interface/scratch.html')

braindump_and_escapeerrands/braindump/interface/templates/interface/goal/glance.html
{% extends 'interface/base.html' %}
{% block title %}Goals at a Glance{% endblock %}
{% load static %}
{% block extra_headers %}
    {# Vis JS #}
    <script src="{% static 'interface/visjs/vis.min.js' %}"></script>
    <link type="text/css" rel="stylesheet" href="{% static 'interface/visjs/vis.min.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'interface/visjs/vis-network.min.css' %}"/>
    {# React & babel JS #}
    <script src="{% static 'interface/reactjs/react.js' %}"></script>
    <script src="{% static 'interface/reactjs/react-dom.js' %}"></script>
    <script src="{% static 'interface/reactjs/babel.js' %}"></script>
    {# Moment JS #}
    <script src="{% static 'interface/momentjs/moment.js' %}"></script>
    {# App JS #}
    <script src="{% static 'interface/appjs/utils.jsx' %}"></script>
    <script src="{% static 'interface/appjs/time-formatter.jsx' %}"></script>
    <link type="text/css" rel="stylesheet"
          href="{% static 'interface/appjs/goal/glance/goal-create-view.css' %}"/>
    <script src="{% static 'interface/appjs/goal/glance/goal-create-view.jsx' %}" type="text/babel"></script>
    <link type="text/css" rel="stylesheet"
          href="{% static 'interface/appjs/goal/glance/goal-search-view.css' %}"/>
    <script src="{% static 'interface/appjs/goal/glance/goal-search-view.jsx' %}" type="text/babel"></script>
    <link type="text/css" rel="stylesheet"
          href="{% static 'interface/appjs/goal/glance/goal-detail-view.css' %}"/>
    <script src="{% static 'interface/appjs/goal/glance/goal-detail-view.jsx' %}" type="text/babel"></script>
    <link type="text/css" rel="stylesheet"
          href="{% static 'interface/appjs/goal/glance/goal-canvas-view.css' %}"/>
    <script src="{% static 'interface/appjs/goal/glance/goal-canvas-view.jsx' %}" type="text/babel"></script>
    <script src="{% static 'interface/appjs/goal/glance/goal-glance-view.jsx' %}" type="text/babel"></script>
{% endblock %}
{% block body %}
    <script type="text/babel">
        ReactDOM.render(<GoalGlanceView
            readFamilyUrl='{% url 'interface:goal_read_family' 1729 %}'
            addRelationUrl='{% url 'interface:goal_add_relation' %}'
            removeRelationUrl="{% url 'interface:goal_remove_relation' %}"
            createUrl="{% url 'interface:goal_create' %}"
            updateUrl="{% url 'interface:goal_update' %}"
            chainUpdateUrl="{% url 'interface:goal_chain_update' %}"
            toggleIsAchievedUrl="{% url 'interface:goal_toggle_is_achieved' 1729 %}"
            deleteIfSingleUrl="{% url 'interface:goal_delete_if_single' %}"
            readRegexUrl="{% url 'interface:goal_read_regex' %}"
        />, document.getElementById('app'));
    </script>
    <div class="container-fluid">
        <div id="app"></div>
    </div>
{% endblock %}

braindump_and_escapeerrands/braindump/interface/templates/interface/goal/snapshot_viewer.html
{% extends 'interface/base.html' %}
{% block title %}Goals at a Glance{% endblock %}
{% load static %}
{% block extra_headers %}
    {# Materialize JS #}
    <script src="{% static 'interface/materialize/materialize.min.js' %}"></script>
    {# React & babel JS #}
    <script src="{% static 'interface/reactjs/react.js' %}"></script>
    <script src="{% static 'interface/reactjs/react-dom.js' %}"></script>
    <script src="{% static 'interface/reactjs/babel.js' %}"></script>
    {# Moment JS #}
    <script src="{% static 'interface/momentjs/moment.js' %}"></script>
    {# App JS #}
    <script src="{% static 'interface/appjs/utils.jsx' %}"></script>
    <link type="text/css" rel="stylesheet"
          href="{% static 'interface/appjs/goal/snapshot_viewer/goal-snapshot.css' %}"/>
    <script src="{% static 'interface/appjs/goal/snapshot_viewer/goal-snapshot-month.jsx' %}"
            type="text/babel"></script>
{% endblock %}
{% block body %}
    <script type="text/babel">
        {# Currently only supports monthly snapshots #}
        ReactDOM.render(<GoalSnapshotMonth
            snapShotMonthUrl="{% url 'interface:goal_snapshot_month' %}"
        />, document.getElementById('app'));
    </script>
    <div class="container-fluid">
        <div id="app" style="width: 100vw; height: 100vh"></div>
    </div>
{% endblock %}