webinterface/urls.py
from django.conf.urls import url
from webinterface.views import goalapis, sessionapis
from webinterface.views import webpages

app_name = 'webinterface'

urlpatterns = [

    # webpages
    # host/scratch/
    url(r'^scratch/$', webpages.scratch, name='scratch'),
    # host/
    url(r'^$', webpages.index, name='index'),
    # host/goal/glance/
    url(r'^goal/glance/$', webpages.goal_glance, name='goal_glance'),

    # sessionapis
    # host/login/<POST password>
    url(r'^login/$', sessionapis.login, name='login'),
    # host/logout/
    url(r'^logout/$', sessionapis.logout, name='logout'),

    # goalapis
    # read
    # host/goal/read/regex/?regex=REGEX_PATTERN & global_search=(1 or 0)
    url(r'^goal/read/regex/$', goalapis.read_regex, name='goal_read_regex'),
    # host/goal/read/family/pk
    url(r'^goal/read/family/(?P<pk>[1-9][0-9]*)/$', goalapis.read_family, name='goal_read_family'),
    # write
    # host/goal/create/<POST description, deadline>
    url(r'^goal/create/$', goalapis.create, name='goal_create'),
    # host/goal/update/<POST id, description, deadline>
    url(r'^goal/update/$', goalapis.update, name='goal_update'),
    # host/goal/delete/if_single/<POST id>
    url(r'^goal/delete/if_single/$', goalapis.delete_if_single, name='goal_delete_if_single'),
    # host/goal/add_relation/<POST parent_id, child_id>
    url(r'^goal/add_relation/$', goalapis.add_relation, name='goal_add_relation'),
    # host/goal/remove_relation/<POST parent_id, child_id>
    url(r'^goal/remove_relation/$', goalapis.remove_relation, name='goal_remove_relation'),
    # host/goal/toggle/is_achieved/pk
    url(r'^goal/toggle/is_achieved/(?P<pk>[1-9][0-9]*)/$', goalapis.toggle_is_achieved,
        name='goal_toggle_is_achieved'),
]

webinterface/templates/webinterface/index/index.html
{% extends 'webinterface/base.html' %}
{% load static %}
{% block extra_headers %}
    {# JQuery #}
    <script src="{% static 'webinterface/materialize/materialize.min.js' %}"></script>
    {# React & babel JS #}
    <script src="{% static 'webinterface/reactjs/react.js' %}"></script>
    <script src="{% static 'webinterface/reactjs/react-dom.js' %}"></script>
    <script src="{% static 'webinterface/reactjs/babel.js' %}"></script>

{% endblock %}
{% block title %}\Errands{% endblock %}
{% block body %}
    <script type="text/babel">
        let LoginLogoutView = React.createClass({
            getInitialState: function () {
                return {
                    isLoggedIn: '{{ isLoggedIn }}' === 'True',
                }
            },
            login: function (password) {
                $.post(this.props.loginUrl, {password: password})
                    .done((r) => {
                        let json = JSON.parse(r);
                        if (json.status === -1) {
                            toastr.error(json.error);
                        } else {
                            this.setState((prevState) => {
                                return {isLoggedIn: !prevState.isLoggedIn}
                            });
                        }
                    })
                    .fail(() => {
                        toastr.error('Server Error');
                    });
            },
            logout: function () {
                $.post(this.props.logoutUrl)
                    .done((r) => {
                        let json = JSON.parse(r);
                        if (json.status === -1) {
                            toastr.error(json.error);
                        } else {
                            this.setState((prevState) => {
                                return {isLoggedIn: !prevState.isLoggedIn}
                            });
                        }
                    })
                    .fail(() => {
                        toastr.error('Server Error');
                    });
            },
            render: function () {
                let ret = '';
                if (!this.state.isLoggedIn) {
                    ret = <div>
                        <span>Not logged in! Login for total access</span>
                        <button className="btn btn-flat" onClick={() => {
                            this.login(this.refs.passwordField.value)
                        }}>Login
                        </button>
                        <label>
                            <input ref="passwordField" type="password"/>
                        </label>
                    </div>;
                } else {
                    ret = <div>
                        <span>Logged In!</span>
                        <button className="btn btn-flat" onClick={() => {
                            this.logout()
                        }}>Logout
                        </button>
                    </div>;
                }
                return ret;
            }
        });

        ReactDOM.render(<LoginLogoutView
                loginUrl='{% url 'webinterface:login' %}'
                logoutUrl='{% url 'webinterface:logout' %}'
            />,
            document.getElementById('app'));
    </script>
    <div class="row" style="position: relative;top: 25vh;">
        <div class="col l4 m4 s4"></div>
        <div class="col l4 m4 s4">
            <div class="card-content center">
                <h1>Escape</h1>
                <div class="flow-text grey-text">(Your)</div>
                <h1>Errands</h1>
            </div>
        </div>
        <div class="col l4 m4 s4">
            <div id="app"></div>
            <ul>
                <li class="center"><a href="{% url 'webinterface:goal_glance' %}">Have a glance on your goals</a></li>
            </ul>
        </div>
    </div>
{% endblock %}