braindump_and_escapeerrands/escapeerrands/cli/urls.py
from django.conf.urls import url

from . import views

app_name = 'cli'

urlpatterns = [
    # host/cli/
    url(r'^$', views.cli, name='cli'),
]

braindump_and_escapeerrands/escapeerrands/errands/urls.py
from django.conf.urls import url

from . import views

app_name = 'errands'

"""
Touch = Create or Update
"""
urlpatterns = [
    # host/errands/all/errands/
    url(r'^all/errands/$', views.all_errands, name='all_errands'),
    # host/errands/touch/errand/pk/
    url(r'^touch/errand/(?P<pk>[0-9]+)/$', views.touch, name='touch_errand'),
    # host/errands/process_touch/errand/
    url(r'^process_touch/errand/$', views.process_touch, name='process_touch_errand'),
    # host/errands/read/errand/pk/
    url(r'^read/errand/(?P<pk>[0-9]+)/$', views.read_errand, name='read_errand'),
    # host/errands/delete/errand/ -- pk is sent through POST method for security
    url(r'^delete/errand/$', views.delete_errand, name='delete_errand'),

    # host/errands/read/piece/pk/
    url(r'^read/piece/(?P<pk>[0-9]+)/$', views.read_piece, name='read_piece'),
    # host/errands/read/stubs/
    url(r'^read/stubs/$', views.read_stubs, name='read_stubs'),
]

braindump_and_escapeerrands/escapeerrands/escapeerrands/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # host/admin/
    url(r'^admin/', admin.site.urls),

    # host
    url(r'^', include('home.urls')),
    # host/errands/
    url(r'^errands/', include("errands.urls")),
    # host/time_table/
    url(r'^time_table/', include("time_table.urls")),
    # host/cli/
    url(r'^cli/', include("cli.urls")),
]

braindump_and_escapeerrands/escapeerrands/home/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'home'

urlpatterns = [
    # host/
    url(r'^$', views.home, name='home'),
    # host/login/
    url(r'^login/$', views.login, name='login'),
    # host/logout/
    url(r'^logout/$', views.logout, name='logout'),
]

braindump_and_escapeerrands/escapeerrands/time_table/urls.py
from django.conf.urls import url

from . import views

app_name = 'time_table'

urlpatterns = [
    # host/time_table/scrolling_stubs/
    url(r'^scrolling_stubs/$', views.scrolling_stubs, name='scrolling_stubs'),
    # host/time_table/verbose/
    url(r'^verbose/$', views.verbose, name='verbose'),
]

braindump_and_escapeerrands/escapeerrands/home/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from errands.models import Errand, Piece
from datetime import datetime as dt, timedelta as td
from django.urls import reverse
from django.http import HttpResponsePermanentRedirect as httpRPR, HttpResponse as httpR
from home.std import Std
import json


def home(request):
    # Accessible to all
    return render(request, 'home/home.html')


def in_session(request):
    if request.session.get(Std.Keys.user_logged_in, False):
        return True
    else:
        return False


def login(request):
    if request.method == 'POST':
        # If User Identity is correct
        if request.POST[Std.Keys.identity] == Std.user_identity:
            # Start Session
            request.session[Std.Keys.user_logged_in] = True
            # Redirect to Client if exists
            if Std.Keys.client_site in request.POST:
                return httpRPR(request.POST[Std.Keys.client_site])
            # Else Redirect to home
            else:
                return httpRPR(reverse('errands:all_errands'))
        # Else
        else:
            return render(request, 'home/invalid_access.html')
    else:
        # Login Page
        return render(request, 'home/login.html')


def logout(request):
    # End Session
    request.session[Std.Keys.user_logged_in] = False
    return httpR(json.dumps({'message': 'Safe Mode Activated'}))

braindump_and_escapeerrands/escapeerrands/home/templates/home/__base__.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% block headers %}
        <meta charset="UTF-8">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <link rel="stylesheet" href="{% static 'home/css/jquery-ui.min.css' %}">
        <script src="{% static 'home/js/jquery-ui.min.js' %}"></script>
        <script src="{% static 'home/js/touchpunch.js' %}"></script>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon" href="{% static 'home/images/logo/web.png' %}">
        <script src="{% static 'home/js/base.js' %}"></script>
        <script src="{% static 'home/js/highcharts.js' %}"></script>
        <script src="{% static 'home/js/moment.js' %}"></script>
        <script src="{% static 'home/js/std.js' %}"></script>
    {% endblock %}
    {% block extra_headers %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
    {% block script %}{% endblock %}
    {% block style %}{% endblock %}
    <script>
        $(document).ready(function () {
            // Materialize CSS
            $('.button-collapse').sideNav({
                    menuWidth: 300, // Default is 240
                    edge: 'left', // Choose the horizontal origin
                    closeOnClick: false, // Closes side-nav on <a> clicks,
                    draggable: true // Choose whether you can drag to open on touch screens
                }
            );
            $(".modal").modal({
                in_duration: 300, // Transition in duration
                out_duration: 200 // Transition out duration
            });

            // Safe-Mode Ajax
            $('#nav-bar').on(
                'click',
                '#safe-mode',
                function () {
                    $.ajax({
                        url: "{% url 'home:logout' %}",
                        error: function () {
                            Materialize.toast('Error going into Safe Mode', 2000);
                        },
                        success: function (result) {
                            result = JSON.parse(result);
                            Materialize.toast(result.message, 1000);
                        }
                    });
                }
            );
        });
    </script>
</head>
<body>

<ul id="nav-bar" class="side-nav">
    <li>
        <div class="userView">
            <div class="background">
                <img src="https://media.giphy.com/media/l3zoKeX8bMG5sMP4s/giphy.gif" class="bg">
            </div>
            <a href="#"><img class="circle" src="{% static 'home/images/my.jpg' %}" alt="icon"></a>
            <a href="#"><span class="white-text name">Yashasvi Sriram</span></a>
            <a href="#"><span class="white-text email">yash.3997@gmail.com</span></a>
        </div>
    </li>
    <li><a href="{% url 'home:home' %}" class="waves-effect"><i class="material-icons">home</i>Home</a></li>
    <li><a href="{% url 'errands:all_errands' %}" class="waves-effect"><i class="material-icons">receipt</i>Errands</a></li>
    <li><a href="{% url 'time_table:scrolling_stubs' %}" class="waves-effect"><i class="material-icons">view_week</i>TimeTable</a>
    <li><a href="{% url 'cli:cli' %}" class="waves-effect"><i class="material-icons">settings_ethernet</i>CLI</a>
    <li><a id="safe-mode" href="#" class="waves-effect"><i class="material-icons">verified_user</i>Safe Mode</a>
</ul>

<a href="#"
   id="nav-bar-fab"
   data-activates="nav-bar"
   class="btn-floating btn-large button-collapse z-depth-4"
   style="position: fixed;bottom: 0;left: 0;margin: 20px;z-index: 200">
    <i class="material-icons">library_books</i>
</a>


{% block body %}{% endblock %}
</body>
</html>

braindump_and_escapeerrands/escapeerrands/home/templates/home/home.html
{% extends 'home/__base__.html' %}
{% block title %}Home{% endblock %}
{% block body %}
    <div class="row" style="position: relative;top: 25vh;">
        <div class="col l0 m0 s0"></div>
        <div class="col l12 m12 s12 center align waves-effect">
            <div class="card-content">
            <h1>Escape</h1>
            <div class="flow-text grey-text">(Your)</div>
            <h2>Errands</h2>
            </div>
        </div>
        <div class="col l0 m0 s0"></div>
    </div>
{% endblock %}

braindump_and_escapeerrands/escapeerrands/home/templates/home/invalid_access.html
{% extends 'home/__base__.html' %}
{% block title %}Invalid Access{% endblock %}
{% block body %}
    {% load static %}
    <div class="row">
        <div class="col l3 m0 s0"></div>
        <div class="col l6 m12 s12 center-align">
            <div>
                <h1 class="red-text">Invalid Access</h1>
                <img style="width: 100%" src="{% static "home/images/invalid_access.gif" %}">
            </div>
        </div>
        <div class="col l3 m0 s0"></div>
    </div>
{% endblock %}

braindump_and_escapeerrands/escapeerrands/home/templates/home/login.html
{% extends 'home/__base__.html' %}
{% block title %}Login{% endblock %}
{% block body %}
    <div class="row">
        <div class="col l3 m0 s0"></div>
        <div class="col l6 m12 s12 center-align">
            <div style="position: relative;top: 10vh;z-index: 201">
                <h3>Who are you?</h3>
                <p class="blue-text flow-text">The content you requested is private. Please Identify Yourself</p>
                <form action="{% url 'home:login' %}" method="post">
                    {% csrf_token %}
                    <div class="input-field">
                        <i class="material-icons prefix">account_circle</i>
                        <input name="Identity" type="password" placeholder="Identity">
                        {% if Client_Site %}
                        <input name="Client_Site" type="hidden" value="{{ Client_Site }}">
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
        <div class="col l3 m0 s0"></div>
    </div>
{% endblock %}